### ISSUE TITLE
RefreshableFlatList.ios.js 中 161 行 this.state.releaseing, state定义的是refreshing

### ISSUE THREAD

**Issue by huangbaoyu** [razor1895/react-native-refreshable-flatlist#2]
onScroll = (event) => {
    const offsetY = event.nativeEvent.contentOffset.y + event.nativeEvent.contentInset.top;
    const contentOffset = this.state.contentHeight - this.state.flatListHeight;
    this.contentOffset = contentOffset;

    if (!this.state.releasing) {
      if (offsetY < -this.props.minPullDownDistance) {
        this.setState({
          offsetY,
          scrollStatus: 'EXCEEDED_MIN_PULL_DOWN_DISTANCE',
        });
      } else if ((contentOffset > 0 && offsetY >= contentOffset + this.props.minPullUpDistance)

**Comment by razor1895** [comment]
感谢反馈，这确实是我粗心导致的，已经改过来了
