### ISSUE TITLE
onRefreshing's callback

### ISSUE THREAD

**Issue by budiga** [razor1895/react-native-refreshable-flatlist#4]
forgive my poor English.
In your [demo](https://gist.github.com/razor1895/2e755135af960752c164fad62f169ec9),onRefreshing is below:
`onRefreshing={() => new Promise((r) => {
            setTimeout(() => {
              r();
            }, 3000);
          })}`
May I write in this way?
`onRefreshing={(r) => {
      setTimeout(() => {
          r();
      }, 3000);
  }`
I want to end refreshing after 3 seconds,but it end refreshing immediately. I don't know why.It's the same to onLoadMore.
Hope your reply，thanks a lot!

**Comment by razor1895** [comment]
here's the logic where triggers `onRefreshing`:
```javascript
      let loadingDataPromise = new Promise((resolve) => {
        const loadDataReturnValue = this.props[action](resolve);

        if (isPromise(loadDataReturnValue)) {
          loadingDataPromise = loadDataReturnValue;
        }

        Promise.all([
          loadingDataPromise,
          new Promise(r => this.setState({ refreshing: true }, r)),
          delay(this.props.minDisplayTime),
        ])
          .then(() => {
            this.flatList.scrollToOffset({ animated: true, offset: resetOffset });
            this.setState({
              refreshing: false,
              scrollStatus: rerestScrollStatus,
            });
          });
      });
```
So, if your onRefreshing prop is not  a `Promise`, it will be executed immediately.
Just wrap your `setTimeout` function with a `Promise` to achieve your goal.

**Comment by budiga** [comment]
OK,it means that I should give a Promise param to the onRefreshing property.May I do a network request like this?
`onRefreshing={() => new Promise((r) => {
    fetch(url,options).then(res => {
       r();
      //...do sth with the response
    });
})}`
Is this right?

**Comment by razor1895** [comment]
Your code would work as your expectation, but the `fetch` api returns a promise, so just write like this:
```javascript
onRefreshing={() => fetch(url, options).then(res => {
  //...do sth with the response
})}

**Comment by budiga** [comment]
@razor1895 get it! Thank you very much !

**Comment by razor1895** [comment]
glad to help you
